###########################################################################
###########################################################################
##
##  Docker Compose File: Jellyfin (LinuxServer.io)
##  Function: Media Server
##
##  Documentation: https://jellyfin.org/docs/general/administration/installing#docker
##  https://jellyfin.org/docs/general/administration/hardware-acceleration/
##
###########################################################################
###########################################################################
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    # Add Configurations for GPU Hardware Rendering Here:
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    volumes:
      - /mnt/<pool name>/configs/jellyfin:/config
      - /mnt/<pool name>/media/Movies/English:/movies/English
      - /mnt/<pool name>/media/Movies/Regional:/movies/Regional
      - /mnt/<pool name>/media/Animated/Animated_Movies:/movies/Animated_Movies
      - /mnt/<pool name>/media/Anime/Anime_Movies:/movies/Anime_Movies
      - /mnt/<pool name>/media/Family_Videos:/movies/Family_Videos
      - /mnt/<pool name>/media/Tv_Shows:/tv/Tv_shows
      - /mnt/<pool name>/media/Animated/Animated_Shows:/tv/Animated_shows
      - /mnt/<pool name>/media/Anime/Anime_Shows:/tv/Anime_shows
    ports:
      - 8096:8096
      # - 7359:7359/udp      # Enable for DLNA - Only works on HOST Network Mode
      # - 1900:1900/udp      # Enable for DLNA - Only works on HOST Network Mode
    environment:
      - PUID=568
      - PGID=568
      - TZ=Asia/Kolkata
      # - JELLYFIN_PublishedServerUrl=${LOCAL_DOCKER_IP:?err}  # Enable for DLNA - Only works on HOST Network Mode
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
