services:
  app:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /mnt/Athena/configs/ninx:/data
      - /mnt/Athena/configs/ninx/certs:/etc/letsencrypt