services:
  photoprism:
    image: photoprism/photoprism:latest
    restart: unless-stopped
    depends_on:
      - mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2342:2342"
    working_dir: "/photoprism" # do not change or remove
    volumes:
      - "/mnt/hostname/photos:/photoprism/originals" # Originals mount path can be changed as needed (DO NOT REMOVE)
      - "/mnt/hostname/configs/photoprism:/photoprism/storage"     # *Writable* storage folder for cache, database, and sidecar files (DO NOT REMOVE)
    # devices:
    #   - /dev/dri/renderD128:/dev/dri/renderD128
    #   - /dev/dri/card0:/dev/dri/card0
    environment:
      - PHOTOPRISM_ADMIN_USER="admin"                 # admin login username
      - PHOTOPRISM_ADMIN_PASSWORD="insecure"          # initial admin password (8-72 characters)
      - PHOTOPRISM_AUTH_MODE="password"               # authentication mode (public, password)
      # - PHOTOPRISM_FFMPEG_ENCODER="nvidia"
      # - PHOTOPRISM_INIT="tensorflow"
      # - NVIDIA_VISIBLE_DEVICES="all"

    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: "nvidia"
    #           count: 1
    #           capabilities: [gpu]


  mariadb:
    image: mariadb:11
    restart: unless-stopped
    stop_grace_period: 5s
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - "./database:/var/lib/mysql" # DO NOT REMOVE