networks:
  recyclarr:
    name: recyclarr
    external: true

services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    user: 1000:1000
    read_only: true
    tmpfs: /tmp
    networks: [recyclarr]
    volumes:
      - ./config:/config
    environment:
      - TZ=Asia/Kolkata