services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - 8120:80
            - 8443:443
        environment:
            - PUID=568
            - PGID=568
            - APP_KEY=base64:pdjyuxmjDSGhsD5M2zwNZleI6wu+i5qeiW/0N3UWeGg= # get the api key from https://speedtest-tracker.dev/
            - DB_CONNECTION=sqlite
            - SPEEDTEST_SCHEDULE=0 0 * * *

            - PRUNE_RESULTS_OLDER_THAN=
            - CHART_DATETIME_FORMAT= 
            - DATETIME_FORMAT=
            - APP_TIMEZONE=Asia/Kolkata
            - DISPLAY_TIMEZONE=Asia/Kolkata
            # - TZ=Asia/Kolkata
        volumes:
            - /mnt/hostname/configs/speedtest:/config
            - /mnt/hostname/configs/speedtest/certs:/config/keys
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped