services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - 8090:80
    environment:
      DOMAIN:  # Your domain here! (that you created in nginx proxy)
      # ADMIN_TOKEN: changeme
    volumes:
      - /mnt/hostname/configs/vaultwarden:/data