services:
  watchtower:
    image: containrrr/watchtower
    environment:
      - TZ=Asia/Kolkata
      - WATCHTOWER_NOTIFICATIONS_HOSTNAME=TrueNas
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_SCHEDULE=0 0 3 * * *
      # - WATCHTOWER_NOTIFICATION_URL=discord://token@webhookid
      # - WATCHTOWER_NOTIFICATIONS=gotify
      # - WATCHTOWER_NOTIFICATION_GOTIFY_URL=https://
      # - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock